replicaCount: 1

image:
  repository: jainambarbhaya15/user-service
  tag: "15"

imagePullSecrets:
  - name: dockerhub-secret-shared


ingress:
  enabled: true
  className: nginx

  hosts:
    - host: dev.userservice.local
      paths:
        - path: /
          pathType: Prefix


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70


dockerConfigJson: e30=