apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-service
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesFile: environment/values-dev.yaml
          - env: prod
            namespace: prod
            valuesFile: environment/values-prod.yaml
  template:
    metadata:
      name: 'user-service-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jainambarbhaya1509/gitops.git'
        targetRevision: main
        path: charts/user-service
        helm:
          valueFiles:
            - ../../{{valuesFile}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      
      # FIXED: Added to stop ArgoCD from tracking the ESO generated secret details
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: dockerhub-secret-shared
          jsonPointers:
            - /data
            - /metadata/annotations
            - /metadata/labels

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
