apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: user-service-prod

  namespace: argocd

spec:

  project: default

  source:

    repoURL: https://github.com/jainambarbhaya1509/gitops.git

    targetRevision: main

    path: charts/user-service

    helm:

      valueFiles:
      - ../../environments/prod/user-service-values.yaml

  destination:

    server: https://kubernetes.default.svc

    namespace: prod

  syncPolicy:

    automated:

      prune: true

      selfHeal: true